### ISSUE TITLE
marquez seed fails with java.net.UnknownHostException: postgres

### ISSUE THREAD

**Issue by OleksandrDvornik** [MarquezProject/marquez#1607]
docker marquez-seed fails with 
ERROR [2021-08-30 17:04:22,208] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.
2021-08-30T17:04:22.210707540Z ! java.net.UnknownHostException: postgres
2021-08-30T17:04:22.210712626Z ! at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
2021-08-30T17:04:22.210716108Z ! at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
2021-08-30T17:04:22.210719101Z ! at java.base/java.net.Socket.connect(Unknown Source)
2021-08-30T17:04:22.210721950Z ! at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
2021-08-30T17:04:22.210724846Z ! at org.postgresql.core.PGStream.<init>(PGStream.java:95)
2021-08-30T17:04:22.210728318Z ! at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
2021-08-30T17:04:22.210731405Z ! at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
2021-08-30T17:04:22.210734962Z ! ... 26 common frames omitted
2021-08-30T17:04:22.210737962Z ! Causing: org.postgresql.util.PSQLException: The connection attempt failed.
2021-08-30T17:04:22.210741430Z ! at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:315)
2021-08-30T17:04:22.210745215Z ! at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
2021-08-30T17:04:22.210748769Z ! at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
2021-08-30T17:04:22.210752423Z ! at org.postgresql.Driver.makeConnection(Driver.java:465)
2021-08-30T17:04:22.210755595Z ! at org.postgresql.Driver.connect(Driver.java:264)
2021-08-30T17:04:22.210758559Z ! at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:347)
2021-08-30T17:04:22.210761835Z ! at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:228)
2021-08-30T17:04:22.210765095Z ! at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:769)
2021-08-30T17:04:22.210768627Z ! at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:697)
2021-08-30T17:04:22.210792572Z ! at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:496)
2021-08-30T17:04:22.210797093Z ! at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
2021-08-30T17:04:22.210800973Z ! at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:121)
2021-08-30T17:04:22.210804347Z ! at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:110)
2021-08-30T17:04:22.210807639Z ! at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:134)
2021-08-30T17:04:22.210810490Z ! at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
2021-08-30T17:04:22.210814504Z ! at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:80)
2021-08-30T17:04:22.210818409Z ! at org.flywaydb.core.Flyway.execute(Flyway.java:453)
2021-08-30T17:04:22.210821474Z ! at org.flywaydb.core.Flyway.info(Flyway.java:331)
2021-08-30T17:04:22.210824370Z ! at marquez.db.DbMigration.hasPendingDbMigrations(DbMigration.java:66)
2021-08-30T17:04:22.210827485Z ! at marquez.db.DbMigration.migrateDbOrError(DbMigration.java:21)
2021-08-30T17:04:22.210830300Z ! at marquez.MarquezApp.run(MarquezApp.java:103)
2021-08-30T17:04:22.210833154Z ! at marquez.MarquezApp.run(MarquezApp.java:49)
2021-08-30T17:04:22.210836131Z ! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
2021-08-30T17:04:22.210839052Z ! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
2021-08-30T17:04:22.210842113Z ! at io.dropwizard.cli.Cli.run(Cli.java:78)
2021-08-30T17:04:22.210845250Z ! at io.dropwizard.Application.run(Application.java:94)
2021-08-30T17:04:22.210848660Z ! at marquez.MarquezApp.main(MarquezApp.java:61)
2021-08-30T17:04:22.211080703Z INFO  [2021-08-30 17:04:22,210] marquez.MarquezApp: Stopping app...

**Comment by wslulciuc** [comment]
> 2021-08-30T17:04:22.210707540Z ! java.net.UnknownHostException: postgres

I ran `./docker/up.sh --seed`, but didn't run into this error. Mind providing the command you used, or making sure the postgres container is running?

**Comment by OleksandrDvornik** [comment]
I used `./docker/up.sh --build`

**Comment by wslulciuc** [comment]
I tried:

```
./docker/up.sh --build
./docker/up.sh --build --seed
```

and didn't run into any issues. What version of Marquez are you running locally?

**Comment by wslulciuc** [comment]
Nothing really sticks out in the logs. Just wonder, was this working before any of our recent releases? That said, it may have something to do with using docker compose [links](https://docs.docker.com/compose/networking/#links) on Linux. Mind also providing the logs for the `api` container using:

```
$ docker logs marquez-api
```
