### ISSUE TITLE
[SPARK] latest notebook docker image fails with CastCastException

### ISSUE THREAD

**Issue by OleksandrDvornik** [MarquezProject/marquez#1608]
When running docker-compose with notebook from integrations/spark with SparkListener, getting bellow exception.
```
from pyspark.sql import SparkSession
file = "/home/jovyan/marquezlib/libs/marquez-spark-0.17.1-SNAPSHOT.jar"
spark = (SparkSession.builder.master('local').appName('rdd_to_dataframe')
             .config('spark.jars', file)
             .config('spark.jars.packages', 'org.postgresql:postgresql:42.2.+')
             .config('spark.extraListeners', 'openlineage.spark.agent.OpenLineageSparkListener')
             .config('openlineage.url', 'http://marquez:5000/api/v1/namespaces/spark_integration/')
             .getOrCreate())
```
the same behavior for marquez.spark.agent.SparkListener

Exception
```
21/08/30 17:13:10 ERROR AsyncEventQueue: Listener OpenLineageSparkListener threw an exception
java.lang.ClassCastException: class java.lang.String cannot be cast to class scala.Option (java.lang.String is in module java.base of loader 'bootstrap'; scala.Option is in unnamed module of loader 'app')
	at io.openlineage.spark.agent.OpenLineageSparkListener.findSparkConfigKey(OpenLineageSparkListener.java:280)
	at io.openlineage.spark.agent.OpenLineageSparkListener.parseConf(OpenLineageSparkListener.java:256)
	at io.openlineage.spark.agent.OpenLineageSparkListener.onApplicationStart(OpenLineageSparkListener.java:243)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:55)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
​
```

**Comment by wslulciuc** [comment]
@OleksandrDvornik: Since we removed the notebook example in #1610, is this still an issue?

**Comment by OleksandrDvornik** [comment]
I'll test it today

**Comment by OleksandrDvornik** [comment]
it works fine for :
```

from pyspark.sql import SparkSession
file = "/home/jovyan/openlineage/libs/marquez-spark-0.17.1-SNAPSHOT.jar"
spark = (SparkSession.builder.master('local').appName('rdd_to_dataframe')
             .config('spark.jars', file)
             .config('spark.jars.packages', 'org.postgresql:postgresql:42.2.+')
             .config('spark.extraListeners', 'marquez.spark.agent.SparkListener')
             .config('spark.openlineage.url', 'http://marquez:5000/api/v1/namespaces/spark_integration/')
             .getOrCreate())
spark.sparkContext.setLogLevel('debug')

df = spark.read.text("/home/jovyan/openlineage/test_data/data.txt")

agg = df.groupBy("value").count()
agg.write.mode("overwrite").csv("/home/jovyan/openlineage/test_data/test_output/")
```

```
INFO OpenLineageContext: Lineage completed successfully: ResponseMessage(responseCode=201, body=null, error=null) {"eventType":"COMPLETE","eventTime":"2021-09-14T15:39:46.507Z","run":{"runId":"d98fb3e7-8245-41d8-b33e-f5ec481d3bba","facets":{"spark.logicalPlan":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.2.2/integration/spark","_schemaURL":"https://openlineage.io/spec/1-0-1/OpenLineage.json#/definitions/CustomFacet","plan":[{"class":"org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand","num-children":1,"outputPath":null,"staticPartitions":null,"ifPartitionNotExists":false,"partitionColumns":[],"fileFormat":null,"options":null,"query":0,"mode":null,"outputColumnNames":"[value, count]"},{"class":"org.apache.spark.sql.catalyst.plans.logical.Aggregate","num-children":1,"groupingExpressions":[[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"value","dataType":"string","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":0,"jvmId":"6d416e8e-8b2d-4411-b816-fe842f2c0663"},"qualifier":[]}]],"aggregateExpressions":[[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"value","dataType":"string","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":0,"jvmId":"6d416e8e-8b2d-4411-b816-fe842f2c0663"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.Alias","num-children":1,"child":0,"name":"count","exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":4,"jvmId":"6d416e8e-8b2d-4411-b816-fe842f2c0663"},"qualifier":[],"explicitMetadata":{},"nonInheritableMetadataKeys":[]},{"class":"org.apache.spark.sql.catalyst.expressions.aggregate.AggregateExpression","num-children":1,"aggregateFunction":0,"mode":{"object":"org.apache.spark.sql.catalyst.expressions.aggregate.Complete$"},"isDistinct":false,"resultId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":3,"jvmId":"6d416e8e-8b2d-4411-b816-fe842f2c0663"}},{"class":"org.apache.spark.sql.catalyst.expressions.aggregate.Count","num-children":1,"children":[0]},{"class":"org.apache.spark.sql.catalyst.expressions.Literal","num-children":0,"value":"1","dataType":"integer"}]],"child":0},{"class":"org.apache.spark.sql.execution.datasources.LogicalRelation","num-children":0,"relation":null,"output":[[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"value","dataType":"string","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":0,"jvmId":"6d416e8e-8b2d-4411-b816-fe842f2c0663"},"qualifier":[]}]],"isStreaming":false}]}}},"job":{"namespace":"spark_integration","name":"rdd_to_dataframe.execute_insert_into_hadoop_fs_relation_command"},"inputs":[{"namespace":"file","name":"/home/jovyan/openlineage/test_data","facets":{"schema":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.2.2/integration/spark","fields":[{"name":"value","type":"string"}],"_schemaURL":"https://openlineage.io/spec/1-0-1/OpenLineage.json#/definitions/SchemaDatasetFacet"},"dataSource":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.2.2/integration/spark","name":"file","uri":"file","_schemaURL":"https://openlineage.io/spec/1-0-1/OpenLineage.json#/definitions/DatasourceDatasetFacet"}}}],"outputs":[{"namespace":"file","name":"/home/jovyan/openlineage/test_data/test_output","facets":{"schema":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.2.2/integration/spark","fields":[{"name":"value","type":"string"},{"name":"count","type":"long"}],"_schemaURL":"https://openlineage.io/spec/1-0-1/OpenLineage.json#/definitions/SchemaDatasetFacet"},"dataSource":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.2.2/integration/spark","name":"file","uri":"file","_schemaURL":"https://openlineage.io/spec/1-0-1/OpenLineage.json#/definitions/DatasourceDatasetFacet"},"stats":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.2.2/integration/spark","_schemaURL":"https://github.com/OpenLineage/OpenLineage/tree/0.2.2/integration/spark/facets/spark-2.4/v1/output-statistics-facet.json","rowCount":0,"size":-1,"status":"DEPRECATED"}},"outputFacets":{"outputStatistics":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.2.2/integration/spark","rowCount":0,"size":-1,"_schemaURL":"https://openlineage.io/spec/1-0-1/OpenLineage.json#/definitions/OutputStatisticsOutputDatasetFacet"}}}],"producer":"https://github.com/OpenLineage/OpenLineage/tree/0.2.2/integration/spark","schemaURL":"https://openlineage.io/spec/1-0-1/OpenLineage.json#/definitions/RunEvent"}```
