### ISSUE TITLE
Exception in marquez-api logs - when jobs.current_location is null?

### ISSUE THREAD

**Issue by rossturk** [MarquezProject/marquez#1644]
I have an exception stack in the logs for my `marquez-api` container:

```
ERROR [2021-09-17 05:25:56,555] marquez.db.Columns: Could not read source URI
! java.net.MalformedURLException: no protocol:
! at java.base/java.net.URL.<init>(Unknown Source)
! at java.base/java.net.URL.<init>(Unknown Source)
! at java.base/java.net.URL.<init>(Unknown Source)
! at marquez.db.Columns.urlOrNull(Columns.java:241)
! at marquez.db.mappers.JobDataMapper.map(JobDataMapper.java:45)
! at marquez.db.mappers.JobDataMapper.map(JobDataMapper.java:27)
! at org.jdbi.v3.core.result.ResultSetResultIterator.next(ResultSetResultIterator.java:83)
```

I looked into JobDataMapper and it only seems to call urlOrNull() for the current_location field. When I look @ that field in my database, it's null for each of my jobs.

I believe this check should prevent the issue I am experiencing, not sure why it isn't 🤔:

https://github.com/MarquezProject/marquez/blob/bcebda69ae06e5f87d1f827aa3adcd8decdc0315/api/src/main/java/marquez/db/Columns.java#L237

**Comment by collado-mike** [comment]
The data is not null, but not a URL. Do you know what the value is? Can you paste the lineage event that was sent?

**Comment by rossturk** [comment]
After some investigation, the value was an empty string. It came in through `dbt-ol`.

IMO, the API should deal with an empty string as if it were a null. It can't always control what the client sends.
