### ISSUE TITLE
The python example for the client API is not working

### ISSUE THREAD

**Issue by fbraza** [MarquezProject/marquez#1671]
When working of this issue #1667, I tried to tied a job to a dataset then set its status as done. Because I was having an error with my code I decided to run the example proposed here https://github.com/MarquezProject/marquez/tree/main/clients/python/examples

While running the script I got this error:

```
Traceback (most recent call last):
  File "example.py", line 63, in <module>
    mark_as_running=True
  File "/home/fbraza/.cache/pypoetry/virtualenvs/marquez-pilot-Cf5KNPOm-py3.7/lib/python3.7/site-packages/marquez_client/client.py", line 306, in create_job_run
    response = self.mark_job_run_as_started(run_id)
  File "/home/fbraza/.cache/pypoetry/virtualenvs/marquez-pilot-Cf5KNPOm-py3.7/lib/python3.7/site-packages/marquez_client/client.py", line 331, in mark_job_run_as_started
    return self.__mark_job_run_as(run_id, 'start', at)
  File "/home/fbraza/.cache/pypoetry/virtualenvs/marquez-pilot-Cf5KNPOm-py3.7/lib/python3.7/site-packages/marquez_client/client.py", line 362, in __mark_job_run_as
    Utils.is_valid_uuid(run_id, 'run_id')
  File "/home/fbraza/.cache/pypoetry/virtualenvs/marquez-pilot-Cf5KNPOm-py3.7/lib/python3.7/site-packages/marquez_client/utils.py", line 59, in is_valid_uuid
    Utils.is_none(variable_value, variable_name)
  File "/home/fbraza/.cache/pypoetry/virtualenvs/marquez-pilot-Cf5KNPOm-py3.7/lib/python3.7/site-packages/marquez_client/utils.py", line 40, in is_none
    raise ValueError(f"{variable_name} must not be None")
ValueError: run_id must not be None
```
Providing an `run_id` did not solve the problem. I got another error
```
Traceback (most recent call last):
  File "/home/fbraza/.cache/pypoetry/virtualenvs/marquez-pilot-Cf5KNPOm-py3.7/lib/python3.7/site-packages/marquez_client/client.py", line 413, in _response
    response.raise_for_status()
  File "/home/fbraza/.cache/pypoetry/virtualenvs/marquez-pilot-Cf5KNPOm-py3.7/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:5000/api/v1/namespaces/my-namespace/jobs/my-job

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example.py", line 58, in <module>
    description='My first job!'
  File "/home/fbraza/.cache/pypoetry/virtualenvs/marquez-pilot-Cf5KNPOm-py3.7/lib/python3.7/site-packages/marquez_client/client.py", line 257, in create_job
    payload=payload
  File "/home/fbraza/.cache/pypoetry/virtualenvs/marquez-pilot-Cf5KNPOm-py3.7/lib/python3.7/site-packages/marquez_client/client.py", line 397, in _put
    return self._response(response, as_json)
  File "/home/fbraza/.cache/pypoetry/virtualenvs/marquez-pilot-Cf5KNPOm-py3.7/lib/python3.7/site-packages/marquez_client/client.py", line 415, in _response
    self._raise_api_error(e)
  File "/home/fbraza/.cache/pypoetry/virtualenvs/marquez-pilot-Cf5KNPOm-py3.7/lib/python3.7/site-packages/marquez_client/client.py", line 421, in _raise_api_error
    raise errors.APIError() from e
marquez_client.errors.APIError
```

Let me know if you need more details from my side

All the best

**Comment by OleksandrDvornik** [comment]
try to remove this line in script:
` mark_as_running=True`

```
active_run = marquez_client.create_job_run(
    namespace_name='my-namespace',
    job_name='my-job',
    mark_as_running=True     <--HERE
)
```
