### ISSUE TITLE
`./docker/up.sh --build --seed` broken

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#2251]
The command:

```
webpack --config webpack.prod.js
```
 if failing with the following error:

```
 => ERROR [marquezproject/marquez-web:0.27.0 7/8] RUN npm run build                                                     1.8s
------
 > [marquezproject/marquez-web:0.27.0 7/8] RUN npm run build:
#0 0.625
#0 0.625 > marquez-ui@1.0.0 build /usr/src/app
#0 0.625 > webpack --config webpack.prod.js
#0 0.625
#0 1.604 [webpack-cli] Failed to load '/usr/src/app/webpack.prod.js' config
#0 1.727 [webpack-cli] TypeError: Cannot read property 'Descendant' of undefined
#0 1.727     at Object.<anonymous> (/usr/src/app/node_modules/renderkid/node_modules/css-select/lib/compile.js:36:56)
#0 1.727     at Module._compile (internal/modules/cjs/loader.js:999:30)
#0 1.727     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
#0 1.727     at Module.load (internal/modules/cjs/loader.js:863:32)
#0 1.727     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
#0 1.727     at Module.require (internal/modules/cjs/loader.js:887:19)
#0 1.727     at require (internal/modules/cjs/helpers.js:74:18)
#0 1.727     at Object.<anonymous> (/usr/src/app/node_modules/renderkid/node_modules/css-select/lib/index.js:29:17)
#0 1.727     at Module._compile (internal/modules/cjs/loader.js:999:30)
#0 1.727     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
#0 1.745 npm ERR! code ELIFECYCLE
#0 1.746 npm ERR! errno 2
#0 1.753 npm ERR! marquez-ui@1.0.0 build: `webpack --config webpack.prod.js`
#0 1.753 npm ERR! Exit status 2
#0 1.754 npm ERR!
#0 1.754 npm ERR! Failed at the marquez-ui@1.0.0 build script.
#0 1.754 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#0 1.759
#0 1.759 npm ERR! A complete log of this run can be found in:
#0 1.760 npm ERR!     /root/.npm/_logs/2022-11-16T21_43_04_982Z-debug.log
------
failed to solve: executor failed running [/bin/sh -c npm run build]: exit code: 2
```

**Comment by tito12** [comment]
I tried to reproduce this error on main branch, but didn't get any error like this. 
Some information about it which I found https://github.com/fb55/css-select/issues/738

**Comment by wslulciuc** [comment]
Thanks, @tito12. I had some stale binaries / deps. Just had to run (which we may want to document or something for the none `npm` experts):

```
$ npm install
```
