### ISSUE TITLE
Jobs/main page view fails to load

### ISSUE THREAD

**Issue by perttus** [MarquezProject/marquez#2462]
As soon as we started to ingest some metadata from Airflow and Spark it fails to load the page. There is only 66 jobs and we are using "airflow" namespace instead of default. 

If I go to /events page the UI loads again and if I change the namespace back to default I can load the main/jobs page again.

I wonder if it's related to that some of the event payloads are so big that the events UI fails to load them. There was some prompt that suggested to load it as json file instead.

I see this error in the console with the empty jobs/main page:
> react-dom.production.min.js:209 TypeError: Cannot read properties of null (reading 'state')
    at Jobs.tsx:121:66
    at Array.map (<anonymous>)
    at t.render (Jobs.tsx:95:27)
    at Fi (react-dom.production.min.js:182:192)
    at Pi (react-dom.production.min.js:181:224)
    at bc (react-dom.production.min.js:263:490)
    at ml (react-dom.production.min.js:246:265)
    at ul (react-dom.production.min.js:246:194)
    at al (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115

**Comment by perttus** [comment]
So it seems that there are some cases where job latestRun is null and this should be handled when trying to read it in `runStateColor`:
https://github.com/MarquezProject/marquez/blob/da3863c4e3c06fbf56cada08d918b9f8a93c60d1/web/src/routes/jobs/Jobs.tsx#L121

It's already being handled in `stopWatchDuration`:
https://github.com/MarquezProject/marquez/blob/da3863c4e3c06fbf56cada08d918b9f8a93c60d1/web/src/routes/jobs/Jobs.tsx#L114
