### ISSUE TITLE
Column lineage doesn't work with symlink dataset

### ISSUE THREAD

**Issue by sophiely** [MarquezProject/marquez#2776]
Listing Dataset threw an exception if one of the dataset has a symlink and a column lineage:

The symlink dataset is now linked in the lineage but this symlink dataset is not necessarily in the same namespace so it can be find. 

```
java.util.NoSuchElementException: No value present
! at java.base/java.util.Optional.get(Optional.java:143)
! at marquez.service.ColumnLineageService.lambda$enrichWithColumnLineage$21(ColumnLineageService.java:224)
! at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
! at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
! at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
! at marquez.service.ColumnLineageService.enrichWithColumnLineage(ColumnLineageService.java:217)
```

**Comment by wslulciuc** [comment]
Fixed https://github.com/MarquezProject/marquez/pull/2775
