### ISSUE TITLE
Unable to check the column lineage and dataset lineage and got below error need some attention

### ISSUE THREAD

**Issue by prabakaran-123** [MarquezProject/marquez#2921]
Read from oracle : oracle://oracledb.cydlut9zgajr.us-east-1.rds.amazonaws.com:1521

![image](https://github.com/user-attachments/assets/aa84887a-5c9f-4f44-bfcb-b6ddd6de4476)
![image](https://github.com/user-attachments/assets/5b9146f1-98ca-4e34-a193-a89a01703c3a)

**Comment by phixMe** [comment]
Hello, Do you happen to have any logs on the server that indicate what your issue is?

**Comment by prabakaran-123** [comment]
@phixMe Here I have attached the logs
lhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" 17
marquez-api-1  | INFO  [2024-10-14 17:51:20,631] marquez.logging.LoggingMdcFilter: status: 200
marquez-api-1  | 172.20.0.4 - - [14/Oct/2024:17:51:20 +0000] "GET /api/v1/namespaces/oracle%3A%2F%2Foracledb.cydlut9zgajr.us-east-1.rds.amazonaws.com%3A1521/jobs?limit=20&offset=0 HTTP/1.1" 200 26 "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" 11
marquez-api-1  | INFO  [2024-10-14 17:51:25,712] marquez.logging.LoggingMdcFilter: status: 200
marquez-api-1  | 172.20.0.4 - - [14/Oct/2024:17:51:25 +0000] "GET /api/v1/namespaces/oracle%3A%2F%2Foracledb.cydlut9zgajr.us-east-1.rds.amazonaws.com%3A1521/datasets?limit=20&offset=0 HTTP/1.1" 200 963 "http://localhost:3000/datasets" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" 27
marquez-api-1  | ERROR [2024-10-14 17:51:27,057] io.dropwizard.jersey.errors.IllegalStateExceptionMapper: Error handling a request: faef7c3122f24251
marquez-api-1  | ! java.lang.IllegalStateException: No match available
marquez-api-1  | ! at java.base/java.util.regex.Matcher.start(Matcher.java:450)
marquez-api-1  | ! at marquez.service.models.NodeId.parts(NodeId.java:233)
marquez-api-1  | ! at marquez.service.models.NodeId.asDatasetId(NodeId.java:257)
marquez-api-1  | ! at marquez.api.BaseResource.throwIfNotExists(BaseResource.java:161)
marquez-api-1  | ! at marquez.api.OpenLineageResource.getLineage(OpenLineageResource.java:118)
marquez-api-1  | ! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
marquez-api-1  | ! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
marquez-api-1  | ! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
marquez-api-1  | ! at java.base/java.lang.reflect.Method.invoke(Method.java:568)
marquez-api-1  | ! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
marquez-api-1  | ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
marquez-api-1  | ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
marquez-api-1  | ! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
marquez-api-1  | ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
marquez-api-1  | ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
marquez-api-1  | ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
marquez-api-1  | ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
marquez-api-1  | ! at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
marquez-api-1  | ! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
marquez-api-1  | ! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
marquez-api-1  | ! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
marquez-api-1  | ! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
marquez-api-1  | ! at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
marquez-api-1  | ! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
marquez-api-1  | ! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
marquez-api-1  | ! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
marquez-api-1  | ! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
marquez-api-1  | ! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
marquez-api-1  | ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
marquez-api-1  | ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
marquez-api-1  | ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
marquez-api-1  | ! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
marquez-api-1  | ! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
marquez-api-1  | ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
marquez-api-1  | ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
marquez-api-1  | ! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
marquez-api-1  | ! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:322)
marquez-api-1  | ! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
marquez-api-1  | ! at io.dropwizard.jetty.ZipExceptionHandlingGzipHandler.handle(ZipExceptionHandlingGzipHandler.java:26)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
marquez-api-1  | ! at org.eclipse.jetty.server.Server.handle(Server.java:516)
marquez-api-1  | ! at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
marquez-api-1  | ! at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
marquez-api-1  | ! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
marquez-api-1  | ! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
marquez-api-1  | ! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
marquez-api-1  | ! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
marquez-api-1  | ! at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
marquez-api-1  | ! at java.base/java.lang.Thread.run(Thread.java:840)
marquez-api-1  | ERROR [2024-10-14 17:51:27,058] marquez.logging.LoggingMdcFilter: status: 500
marquez-api-1  | 172.20.0.4 - - [14/Oct/2024:17:51:27 +0000] "GET /api/v1/lineage?nodeId=dataset:oracle://oracledb.cydlut9zgajr.us-east-1.rds.amazonaws.com:1521:1521/ORCL.SPARKFLOWS.CDC_TEST_01&depth=2 HTTP/1.1" 500 110 "http://localhost:3000/lineage/dataset/oracle%3A%2F%2Foracledb.cydlut9zgajr.us-east-1.rds.amazonaws.com%3A1521/1521%2FORCL.SPARKFLOWS.CDC_TEST_01" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" 13

**Comment by prabakaran-123** [comment]
@phixMe 
if the dataset name start with a number its creating issue and unable to view the lineage graph

Ex. [1521/ORCL.sparkflows.cdc_test_01_newcol](http://localhost:3000/lineage/dataset/oracle%3A%2F%2Foracledb.cydlut9zgajr.us-east-1.rds.amazonaws.com%3A1521/1521%2FORCL.sparkflows.cdc_test_01_newcol)

![image](https://github.com/user-attachments/assets/a8e653a7-6f29-4cf0-8044-a96e229215fa)

**Comment by prabakaran-123** [comment]
@phixMe  Yes, is there any solution to fix it!

**Comment by phixMe** [comment]
This is logistically a complicated thing for us to fix because it is everywhere including our docs and website and promotional materials...

Essentially, we are in this difficult position where we cannot parse connection strings and use the  `:` colon character as delimiters. There are a bunch of edge cases we are exposed to for example `job:trino://trino-integration-test:1337:1234:more:colons` it's really unclear what we consider the namespace we what we consider the job... Fixing this for one user might break it for another.

I think the only way to rectify this is to change the delimiter character for our notational, but it's a breaking change for all kinds of users.

**Comment by prabakaran-123** [comment]
@phixMe  tried with the above branch which you mentioned: 

could you please provide me sample for the node id with delimeter, as I tried end up with below error

 ERROR [2024-10-17 15:16:52,766] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 11abd68c1ed35ebb
marquez-api-1  | ! java.lang.UnsupportedOperationException: Expected NodeId of type dataset with 3 parts. Got: dataset&oracle://oracledb.cydlut9zgajr.us-east-1.rds.amazonaws.com:1521:1521/orcl.cdc_test_01_newcol
marquez-api-1  | ! at marquez.service.models.NodeId.parts(NodeId.java:218)
marquez-api-1  | ! at marquez.service.models.NodeId.asDatasetId(NodeId.java:257)
marquez-api-1  | ! at marquez.api.BaseResource.throwIfNotExists(BaseResource.java:161)
marquez-api-1  | ! at marquez.api.OpenLineageResource.getLineage(OpenLineageResource.java:121)
marquez-api-1  | ! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
marquez-api-1  | ! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
marquez-api-1  | ! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
marquez-api-1  | ! at java.base/java.lang.reflect.Method.invoke(Method.java:569)
marquez-api-1  | ! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
marquez-api-1  | ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
marquez-api-1  | ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
marquez-api-1  | ! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)  
marquez-api-1  | ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
marquez-api-1  | ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
marquez-api-1  | ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
marquez-api-1  | ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
marquez-api-1  | ! at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
marquez-api-1  | ! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
marquez-api-1  | ! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
marquez-api-1  | ! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
marquez-api-1  | ! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
marquez-api-1  | ! at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
marquez-api-1  | ! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
marquez-api-1  | ! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
marquez-api-1  | ! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
marquez-api-1  | ! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
marquez-api-1  | ! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
marquez-api-1  | ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
marquez-api-1  | ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
marquez-api-1  | ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
marquez-api-1  | ! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
marquez-api-1  | ! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
marquez-api-1  | ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
marquez-api-1  | ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
marquez-api-1  | ! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
marquez-api-1  | ! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
marquez-api-1  | ! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:322)
marquez-api-1  | ! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
marquez-api-1  | ! at io.dropwizard.jetty.ZipExceptionHandlingGzipHandler.handle(ZipExceptionHandlingGzipHandler.java:26)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
marquez-api-1  | ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
marquez-api-1  | ! at org.eclipse.jetty.server.Server.handle(Server.java:516)
marquez-api-1  | ! at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
marquez-api-1  | ! at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
marquez-api-1  | ! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
marquez-api-1  | ! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
marquez-api-1  | ! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
marquez-api-1  | ! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
marquez-api-1  | ! at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
marquez-api-1  | ! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
marquez-api-1  | ! at java.base/java.lang.Thread.run(Thread.java:840)


Requesting Url format : 
(http://localhost:5000/api/v1/lineage?depth=2&nodeId=dataset%26oracle://oracledb.cydlut9zgajr.us-east-1.rds.amazonaws.com:1521:1521/orcl.cdc_test_01_newcol)

**Comment by phixMe** [comment]
Yes, the UI would also need an update... I think the easiest way for you to get around this is to intercept the OpenLineage events and prepend a string to the job names, or rename the jobs that you are testing with to not have this property. 

I don't think we can realistically merge anything here without quite a bit of forethought and communication, so that's probably the best I can recommend for now.
