### ISSUE TITLE
does not route properly

### ISSUE THREAD

**Issue by Chaho12** [MarquezProject/marquez#2983]
Hi guys, i am simply following quick start (git clone + `./docker/up`) but things is not going as the way I expected

gives 504 Gateway Timeout when i access web.
- is fine if i change api address to port 5000 (idk why proxy routing is not working properly)

```
marquez-web     | [HPM] Proxy created: /api/v1  -> http://api:5000/
marquez-web     | [HPM] Proxy created: /api/v2beta  -> http://api:5000/
marquez-web     | App listening on port 3000!
...
marquez-web     | [HPM] Error occurred while proxying request xx.xx.x.xxx:3000/api/v1/namespaces to http://api:5000/ [ENOTFOUND] (https://nodejs.org/api/errors.html#errors_common_system_errors)
...
```
```
-- 0.49.0 version shows this error too
^[[24~seed-marquez-with-metadata  | wait-for-it.sh: timeout occurred after waiting 120 seconds for api:5000
seed-marquez-with-metadata  | io.openlineage.client.OpenLineageClientException: java.net.UnknownHostException: api: No address associated with hostname
seed-marquez-with-metadata  |   at io.openlineage.client.transports.HttpTransport.emit(HttpTransport.java:153)
seed-marquez-with-metadata  |   at io.openlineage.client.transports.HttpTransport.emit(HttpTransport.java:118)
seed-marquez-with-metadata  |   at io.openlineage.client.OpenLineageClient.lambda$emit$0(OpenLineageClient.java:86)
seed-marquez-with-metadata  |   at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
seed-marquez-with-metadata  |   at io.openlineage.client.OpenLineageClient.emit(OpenLineageClient.java:86)
seed-marquez-with-metadata  |   at marquez.cli.SeedCommand.run(SeedCommand.java:139)
seed-marquez-with-metadata  |   at io.dropwizard.cli.Cli.run(Cli.java:78)
seed-marquez-with-metadata  |   at io.dropwizard.Application.run(Application.java:94)
seed-marquez-with-metadata  |   at marquez.MarquezApp.main(MarquezApp.java:68)
seed-marquez-with-metadata  | Caused by: java.net.UnknownHostException: api: No address associated with hostname
seed-marquez-with-metadata  |   at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
seed-marquez-with-metadata  |   at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
seed-marquez-with-metadata  |   at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
seed-marquez-with-metadata  |   at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
seed-marquez-with-metadata  |   at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
seed-marquez-with-metadata  |   at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
seed-marquez-with-metadata  |   at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
seed-marquez-with-metadata  |   at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
seed-marquez-with-metadata  |   at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
seed-marquez-with-metadata  |   at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
seed-marquez-with-metadata  |   at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
seed-marquez-with-metadata  |   at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
seed-marquez-with-metadata  |   at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
seed-marquez-with-metadata  |   at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
seed-marquez-with-metadata  |   at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
seed-marquez-with-metadata  |   at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
seed-marquez-with-metadata  |   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
seed-marquez-with-metadata  |   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
seed-marquez-with-metadata  |   at io.openlineage.client.transports.HttpTransport.emit(HttpTransport.java:148)
```

marquez version : 0.50.0

$ docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:04:24 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

**Comment by Chaho12** [comment]
i notice this is because of code here
- https://github.com/MarquezProject/marquez/blob/main/docker-compose.web.yml#L11

**Comment by dolfinus** [comment]
You should check logs of `api` container, it is probably failing and restarting over and over.

**Comment by hansonglingege** [comment]
> i notice this is because of code here
> 
> * https://github.com/MarquezProject/marquez/blob/main/docker-compose.web.yml#L11

Do you solved this problem？
