### ISSUE TITLE
Error running docker-compose up

### ISSUE THREAD

**Issue by msilvestre** [MarquezProject/marquez#840]
Hi,

I'm trying to run` docker-compose up` but I'm getting this error:

```
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory
```

Any ideia of what could be wrong?

Thank you

**Comment by msilvestre** [comment]
Never mind..

I didn't had docker running :(

So sorry...

**Comment by wslulciuc** [comment]
@msilvestre Great to hear you were able to resolve the issue!
